/*
    This file was generated by `root_dir`/gen_lut.py
*/

module rectangular_lut #(
    localparam int OUT_WIDTH = 16,
    localparam int LUT_SIZE = 32,
    localparam int SEL_WIDTH = $clog2(LUT_SIZE)
) (
    output logic signed [OUT_WIDTH-1:0] rectangular_o,
    input  logic                        clk,
    input  logic                        rst_n,
    input  logic        [SEL_WIDTH-1:0] lut_sel,
    input  logic        [SEL_WIDTH-1:0] duty_cycle
);

always_ff @(posedge clk) begin
    if (!rst_n) begin
        rectangular_o <= 0;
    end else begin
        rectangular_o <= (lut_sel < duty_cycle) ? 16'sd32767 : -16'sd32767;
    end
end

endmodule
