/*
    This file was generated by `root_dir`/gen_lut.py
*/

module triangular_lut #(
    localparam int OUT_WIDTH = 16,
    localparam int LUT_SIZE = 16,
    localparam int SEL_WIDTH = $clog2(LUT_SIZE)
) (
    output logic signed [OUT_WIDTH-1:0] triangular_o,
    input  logic                        clk,
    input  logic                        rst_n,
    input  logic        [SEL_WIDTH-1:0] lut_sel
);

always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        triangular_o <= 0;
    end else begin
        case(lut_sel)
            0: triangular_o <= -16'sd32767;
            1: triangular_o <= -16'sd24575;
            2: triangular_o <= -16'sd16384;
            3: triangular_o <= -16'sd8192;
            4: triangular_o <= 16'sd0;
            5: triangular_o <= 16'sd8192;
            6: triangular_o <= 16'sd16384;
            7: triangular_o <= 16'sd24575;
            8: triangular_o <= 16'sd32767;
            9: triangular_o <= 16'sd24575;
            10: triangular_o <= 16'sd16384;
            11: triangular_o <= 16'sd8192;
            12: triangular_o <= 16'sd0;
            13: triangular_o <= -16'sd8192;
            14: triangular_o <= -16'sd16384;
            15: triangular_o <= -16'sd24575;
        endcase
    end
end

endmodule
